modLoader="javafml"
loaderVersion="[1,)"
license="MIT NON-AI"
issueTrackerURL="https://github.com/Metallurgists-of-Create/Metallurgica/issues"

[[mods]]
modId="metallurgica"
version="${mod_version}"
displayName="Metallurgica"
displayURL="https://github.com/Metallurgists-of-Create/Metallurgica"
logoFile="metallurgica.png"
credits="Metallurgists of Create"
authors="PouffyDev"
description='''
{mod_description}
'''

[[mixins]]
config = "metallurgica.mixins.json"


[[dependencies.metallurgica]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.metallurgica]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.metallurgica]]
modId="kubejs"
type="optional"
versionRange="[${kubejs_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.metallurgica]]
modId="tfmg"
type="required"
versionRange="[{$tfmg_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.metallurgica]]
modId="create"
type="required"
versionRange="[6.0.10,)"
ordering="NONE"
side="BOTH"